apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: product-engine
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  MCP_SERVER_URL: "http://recommendation-server.product-engine.svc.cluster.local:80/sse"
