apiVersion: v1
kind: Service
metadata:
  name: recommendation-server
  namespace: product-engine
spec:
  selector:
    app: recommendation-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
